import { invoke } from '@tauri-apps/api/core'
import { listen } from '@tauri-apps/api/event'
import type { AgentEvent, AgentModel, AgentMode, AgentView, ShellView, AgentResponse, AttachedDocument, CheckProgress, CliStatus, CheckSummary, ContextUsage, Effort, PrStatus, SessionChange, SlashCommand, FileEntry, GitStatus, McpServer, ModelInfo, ProbeResult, ProjectInfo, ProviderView, RemoteInfo, RewindResult, SearchResults, IndexStatus, SessionSnapshot, SessionSummary, ImportProgress, ImportScan, SkillView, CustomAgent, TeamAgent, TeamArtifact, TeamEvent, TeamPost, TeamSearchHit, TeamTask, TeamTaskSummary, TeamTaskFile, TeamTreeInfo, TeamQueued, AgentCommand, TerminalLaunch, TrustStatus, VoiceView } from './types'
import type { ApiFormat } from './providerCatalog'
import type { Route } from './lib/browser'

export const api = {
  listTeamAgents: (refresh = false) => invoke<TeamAgent[]>('list_team_agents', { refresh }),
  listTeamTasks: () => invoke<TeamTaskSummary[]>('list_team_tasks'),
  createTeamTask: (title: string, projectPath: string, members: { kind: string; model?: string; mode?: string }[], newProject = false) => invoke<TeamTask>('create_team_task', { title, projectPath, members, newProject }),
  teamAttach: (id: string, paths: string[], data?: [string, string][]) => invoke<string[]>('team_attach', { id, paths, data: data ?? null }),
  teamSnapshot: (id: string) => invoke<TeamTask>('team_snapshot', { id }),
  addTeamMember: (id: string, member: { kind: string; model?: string; mode?: string }) => invoke<TeamTask>('add_team_member', { id, member }),
  updateTeamMember: (id: string, handle: string, change: { model?: string; mode?: string; effort?: string }) => invoke<TeamTask>('update_team_member', { id, handle, model: change.model ?? null, mode: change.mode ?? null, effort: change.effort ?? null }),
  setTeamWorktree: (id: string, handle: string, enabled: boolean) => invoke<TeamTask>('set_team_worktree', { id, handle, enabled }),
  removeTeamMember: (id: string, handle: string) => invoke<TeamTask>('remove_team_member', { id, handle }),
  renameTeamTask: (id: string, title: string) => invoke<TeamTask>('rename_team_task', { id, title }),
  setTeamRouting: (id: string, enabled: boolean) => invoke<TeamTask>('set_team_routing', { id, enabled }),
  deleteTeamTask: (id: string, cleanup?: { removeWorktrees?: boolean; deleteBranches?: boolean; force?: boolean }) => invoke<void>('delete_team_task', { id, removeWorktrees: cleanup?.removeWorktrees ?? null, deleteBranches: cleanup?.deleteBranches ?? null, force: cleanup?.force ?? null }),
  teamCleanupInfo: (id: string) => invoke<TeamTreeInfo[]>('team_cleanup_info', { id }),
  setTeamAppearance: (id: string, change: { group?: string; icon?: string; color?: string }) => invoke<TeamTask>('set_team_appearance', { id, group: change.group ?? null, icon: change.icon ?? null, color: change.color ?? null }),
  updateTeamQueue: (id: string, change: { item?: string; text?: string; remove?: boolean; delta?: number; paused?: boolean; sendNow?: boolean }) => invoke<TeamQueued[]>('update_team_queue', { id, item: change.item ?? null, text: change.text ?? null, remove: change.remove ?? null, delta: change.delta ?? null, paused: change.paused ?? null, sendNow: change.sendNow ?? null }),
  rerunTeamSetup: (id: string, handle: string) => invoke<void>('rerun_team_setup', { id, handle }),
  teamTaskChanges: (id: string) => invoke<TeamTaskFile[]>('team_task_changes', { id }),
  teamPrStatus: (id: string, handle?: string) => invoke<PrStatus | null>('team_pr_status', { id, handle: handle ?? null }),
  teamFailedLog: (id: string, handle?: string) => invoke<string>('team_failed_log', { id, handle: handle ?? null }),
  teamTaskCwd: (id: string, handle?: string) => invoke<string>('team_task_cwd', { id, handle: handle ?? null }),
  teamTerminalLaunch: (id: string, handle: string) => invoke<TerminalLaunch>('team_terminal_launch', { id, handle }),
  listAgentModels: (kind: string) => invoke<AgentModel[]>('list_agent_models', { kind }),
  listAgentCommands: () => invoke<AgentCommand[]>('list_agent_commands'),
  setAgentPath: (kind: string, path: string | null) => invoke<void>('set_agent_path', { kind, path }),
  agentLatestVersion: (kind: string) => invoke<string | null>('agent_latest_version', { kind }),
  installAgent: (kind: string, version?: string) => invoke<string>('install_agent', { kind, version: version ?? null }),
  setTeamExecution: (id: string, executor: string, reviewer: string, maxRounds: number) => invoke<TeamTask>('set_team_execution', { id, executor, reviewer, maxRounds }),
  runTeamExecution: (id: string) => invoke<void>('run_team_execution', { id }),
  stopTeamExecution: (id: string) => invoke<void>('stop_team_execution', { id }),
  exportTeamUsage: (id: string, destination: string) => invoke<number>('export_team_usage', { id, destination }),
  sendTeamMessage: (id: string, text: string, to: string[]) => invoke<TeamPost>('send_team_message', { id, text, to }),
  stopTeam: (id: string, handle?: string) => invoke<void>('stop_team', { id, handle: handle ?? null }),
  cancelTeamRouting: (id: string) => invoke<void>('cancel_team_routing', { id }),
  listTeamArtifacts: (id: string) => invoke<TeamArtifact[]>('list_team_artifacts', { id }),
  readTeamArtifact: (id: string, path: string) => invoke<string>('read_team_artifact', { id, path }),
  writeTeamArtifact: (id: string, path: string, content: string) => invoke<TeamArtifact[]>('write_team_artifact', { id, path, content }),
  undoTeamTurn: (id: string, postId: string) => invoke<TeamTask>('undo_team_turn', { id, postId }),
  forkTeamMember: (id: string, handle: string) => invoke<TeamTask>('fork_team_member', { id, handle }),
  askTeamSide: (id: string, handle: string, text: string) => invoke<TeamPost>('ask_team_side', { id, handle, text }),
  teamOpenTerminal: (id: string, handle: string) => invoke<void>('team_open_terminal', { id, handle }),
  sweepTeamWorktrees: (id: string) => invoke<{ removed: string[]; kept: string[] }>('sweep_team_worktrees', { id }),
  setTeamPinned: (id: string, pinned: boolean) => invoke<TeamTask>('set_team_pinned', { id, pinned }),
  setTeamLabels: (id: string, labels: string[]) => invoke<TeamTask>('set_team_labels', { id, labels }),
  searchTeam: (query: string) => invoke<TeamSearchHit[]>('search_team', { query }),
  listCustomAgents: () => invoke<CustomAgent[]>('list_custom_agents'),
  setTeamArtifactStatus: (id: string, path: string, status: string) => invoke<TeamArtifact[]>('set_team_artifact_status', { id, path, status }),
  exportTeamArtifacts: (id: string, paths: string[], destination: string) => invoke<number>('export_team_artifacts', { id, paths, destination }),
  teamAgentLogin: (kind: string) => invoke<void>('team_agent_login', { kind }),
  setGeminiKey: (key: string) => invoke<void>('set_gemini_key', { key }),
  scanImports: (sinceDays: number) => invoke<ImportScan>('scan_imports', { sinceDays }),
  importChats: (keys: string[]) => invoke<string[]>('import_chats', { keys }),
  onImportProgress: (handler: (progress: ImportProgress) => void) => listen<ImportProgress>('imports://progress', event => handler(event.payload)),
  importServers: (keys: string[]) => invoke<number>('import_servers', { keys }),
  importRules: (paths: string[]) => invoke<number>('import_rules', { paths }),
  onTeamEvent: (handler: (event: TeamEvent) => void) => listen<TeamEvent>('team://event', event => handler(event.payload)),
  currentProject: () => invoke<ProjectInfo | null>('current_project'),
  recentProjects: () => invoke<string[]>('recent_projects'),
  listSessions: () => invoke<SessionSummary[]>('list_sessions'),
  listAllSessions: () => invoke<SessionSummary[]>('list_all_sessions'),
  currentSession: () => invoke<SessionSnapshot | null>('current_session'),
  createSession: (worktree = false) => invoke<SessionSnapshot>('create_session', { worktree }),
  createChatSession: () => invoke<SessionSnapshot>('create_chat_session'),
  sessionSnapshot: (id: string) => invoke<SessionSnapshot>('session_snapshot', { id }),
  rewindSession: (userIndex: number, restoreCode: boolean) => invoke<RewindResult>('rewind_session', { userIndex, restoreCode }),
  sessionContext: (sessionId: string) => invoke<ContextUsage>('session_context', { sessionId }),
  compactSession: (sessionId: string, instructions?: string) => invoke<ContextUsage>('compact_session', { sessionId, instructions: instructions ?? null }),
  /** Asks the provider for the model's window and the key's quotas, then returns the session's use. */
  refreshContext: (sessionId: string | null) => invoke<ContextUsage>('refresh_context', { sessionId }),
  sessionChanges: () => invoke<SessionChange[]>('session_changes'),
  listCommands: () => invoke<SlashCommand[]>('list_commands'),
  expandCommand: (name: string, args: string) => invoke<string>('expand_command', { name, args }),
  pullRequestStatus: () => invoke<PrStatus | null>('pull_request_status'),
  failedCheckLog: () => invoke<string>('failed_check_log'),
  selectSession: (id: string) => invoke<SessionSnapshot>('select_session', { id }),
  renameSession: (id: string, title: string) => invoke<SessionSummary>('rename_session', { id, title }),
  /** Asks the model for a short task title after the first reply; null when already titled. */
  listSkills: () => invoke<SkillView[]>('list_skills'),
  importSkills: (paths: string[]) => invoke<SkillView[]>('import_skills', { paths }),
  removeSkill: (name: string) => invoke<SkillView[]>('remove_skill', { name }),
  openSkillsFolder: () => invoke<void>('open_skills_folder'),
  setSkillEnabled: (name: string, enabled: boolean) => invoke<SkillView[]>('set_skill_enabled', { name, enabled }),
  /** Custom sub-agents of the open project, plus personal ones. */
  listAgents: () => invoke<AgentView[]>('list_agents'),
  /** Commands the agent left running in the background; one session's when given. */
  listShells: (sessionId?: string) => invoke<ShellView[]>('list_shells', { sessionId: sessionId ?? null }),
  stopShell: (id: string) => invoke<void>('stop_shell', { id }),
  cliStatus: () => invoke<CliStatus>('cli_status'),
  /** Puts the CLI bundled with this app on the PATH. */
  cliInstallPath: () => invoke<CliStatus>('cli_install_path'),
  autoTitleSession: (sessionId: string) => invoke<SessionSummary | null>('auto_title_session', { sessionId }),
  deleteSession: (id: string) => invoke<SessionSnapshot>('delete_session', { id }),
  // The project's own .mcp.json connectors follow the open project; they reconnect in the background.
  openProject: (path: string) => invoke<ProjectInfo>('open_project', { path }).then(info => { void invoke('mcp_sync_project').catch(() => undefined); return info }),
  cloneProject: (url: string, destination: string) => invoke<ProjectInfo>('clone_project', { url, destination }),
  listDirectory: (path?: string) => invoke<FileEntry[]>('list_directory', { path }),
  readFile: (path: string) => invoke<string>('read_file', { path }),
  searchText: (query: string, options: { caseSensitive?: boolean; wholeWord?: boolean; regex?: boolean; glob?: string } = {}) => invoke<SearchResults>('search_text', { query, ...options }),
  listProjectFiles: () => invoke<string[]>('list_project_files'),
  indexStatus: () => invoke<IndexStatus>('index_status'),
  /** Checks the disk for edits made outside Neru; the tree hears about them through workspace://changed. */
  indexRefresh: () => invoke<IndexStatus>('index_refresh'),
  /** Fuzzy file finder over the project index, best match first. */
  searchFiles: (query: string, limit = 60) => invoke<string[]>('search_files', { query, limit }),
  gitStatus: () => invoke<GitStatus>('git_status'),
  gitDiff: (path?: string, staged = false) => invoke<string>('git_diff', { path, staged }),
  gitStage: (path: string) => invoke<void>('git_stage', { path }),
  gitUnstage: (path: string) => invoke<void>('git_unstage', { path }),
  gitCommit: (message: string) => invoke<string>('git_commit', { message }),
  gitBranches: () => invoke<string[]>('git_branches'),
  gitCreateBranch: (name: string) => invoke<string>('git_create_branch', { name }),
  gitRemoteInfo: () => invoke<RemoteInfo>('git_remote_info'),
  gitPush: () => invoke<string>('git_push'),
  createPullRequest: (title?: string, body?: string) => invoke<{ url: string; created: boolean }>('create_pull_request', { title, body }),
  mergePullRequest: () => invoke<string>('merge_pull_request'),
  gitFetch: () => invoke<string>('git_fetch'),
  gitPull: () => invoke<string>('git_pull'),
  gitCheckout: (name: string) => invoke<string>('git_checkout', { name }),
  gitMerge: (name: string) => invoke<string>('git_merge', { name }),
  gitRebase: (name: string) => invoke<string>('git_rebase', { name }),
  gitStash: (action: 'push' | 'pop') => invoke<string>('git_stash', { action }),
  saveFile: (path: string, content: string) => invoke<string>('save_file', { path, content }),
  openInEditor: (path: string) => invoke<void>('open_in_editor', { path }),
  forgetProject: (path: string) => invoke<string[]>('forget_project', { path }),
  revealPath: (path: string) => invoke<void>('reveal_path', { path }),
  fileAction: (action: 'new_file' | 'new_folder' | 'rename' | 'duplicate' | 'delete', path: string, to?: string) => invoke<string>('file_action', { action, path, to: to ?? null }),
  previewHint: () => invoke<{ command: string; url: string }>('preview_hint'),
  previewStart: () => invoke<{ command: string; url: string }>('preview_start'),
  previewCurrent: () => invoke<{ command: string; url: string } | null>('preview_current'),
  previewStop: () => invoke<void>('preview_stop'),
  previewRoute: (url: string) => invoke<Route>('preview_route', { url }),
  proposeFile: (path: string, content: string) => invoke<{ diff: string }>('propose_file', { path, content }),
  applyPending: () => invoke<string>('apply_pending'),
  rejectPending: () => invoke<void>('reject_pending'),
  /** Answers a plan from exit_plan_mode; returns the mode the session continues in. */
  resolvePlan: (sessionId: string | null, approve: boolean, mode: AgentMode | null, feedback: string | null) => invoke<AgentMode>('resolve_plan', { sessionId, approve, mode, feedback }),
  /** One answer per question; several choices joined by ", ". */
  answerQuestion: (sessionId: string | null, answers: string[]) => invoke<void>('answer_question', { sessionId, answers }),
  restoreCheckpoint: (id: string) => invoke<void>('restore_checkpoint', { id }),
  configureProvider: (providerId: string, apiFormat: ApiFormat, baseUrl: string, apiKey: string, model: string) => invoke<ProviderView>('configure_provider', { providerId, apiFormat, baseUrl, apiKey, model }),
  providerStatus: () => invoke<ProviderView>('provider_status'),
  newChat: () => invoke<void>('new_chat'),
  forkSession: (id: string) => invoke<SessionSnapshot>('fork_session', { id }),
  listModels: (providerId: string, apiFormat: ApiFormat, baseUrl: string, apiKey: string) => invoke<ModelInfo[]>('list_models', { providerId, apiFormat, baseUrl, apiKey }),
  answerSubagentApproval: (requestId: string, approve: boolean) => invoke<void>('answer_subagent_approval', { requestId, approve }),
  probeModel: (providerId: string, apiFormat: ApiFormat, baseUrl: string, apiKey: string, model: string, force = false) => invoke<ProbeResult>('probe_model', { providerId, apiFormat, baseUrl, apiKey, model, force }),
  checkModels: (runId: string, providerId: string, baseUrl: string, apiKey: string, targets: { model: string; apiFormat: ApiFormat }[]) => invoke<CheckSummary>('check_models', { runId, providerId, baseUrl, apiKey, targets }),
  cancelCheckModels: (runId: string) => invoke<void>('cancel_check_models', { runId }),
  onModelCheck: (handler: (progress: CheckProgress) => void) => listen<CheckProgress>('models://check', event => handler(event.payload)),
  chat: (options: { prompt: string; contextPaths: string[]; mode: AgentMode; web: boolean; documents: AttachedDocument[]; effort: Effort; sessionId: string | null; notes?: string | null; surface?: 'chat' | 'code' }) => invoke<AgentResponse>('ai_chat', {
    prompt: options.prompt, contextPaths: options.contextPaths, mode: options.mode, web: options.web, surface: options.surface ?? 'code',
    documents: options.documents.filter(doc => doc.kind !== 'image').map(doc => ({ path: doc.path, text: doc.text ?? null, name: doc.kind === 'element' ? doc.name : null, kind: doc.kind === 'element' ? 'element' : null })),
    images: options.documents.filter(doc => doc.kind === 'image' && doc.dataUrl).map(doc => ({ name: doc.name, dataUrl: doc.dataUrl })),
    effort: options.effort === 'auto' ? null : options.effort, sessionId: options.sessionId, notes: options.notes ?? null,
  }),
  inspectDocuments: (paths: string[]) => invoke<AttachedDocument[]>('inspect_documents', { paths }),
  documentBytes: (path: string) => invoke<ArrayBuffer>('document_bytes', { path }),
  readImage: (path: string) => invoke<string>('read_image', { path }),
  effortSupported: () => invoke<boolean>('effort_supported'),
  forgetKeys: () => invoke<void>('forget_keys'),
  savedKeyProviders: () => invoke<string[]>('saved_key_providers'),
  mcpServers: () => invoke<McpServer[]>('mcp_servers'),
  mcpSaveServer: (server: Pick<McpServer, 'name' | 'command' | 'args' | 'env' | 'url' | 'headers' | 'enabled'>, previous?: string) => invoke<McpServer[]>('mcp_save_server', { server, previous }),
  mcpRemoveServer: (name: string) => invoke<McpServer[]>('mcp_remove_server', { name }),
  mcpRestart: (name: string) => invoke<McpServer[]>('mcp_restart', { name }),
  mcpSyncProject: () => invoke<McpServer[]>('mcp_sync_project'),
  mcpSignIn: (name: string) => invoke<McpServer[]>('mcp_sign_in', { name }),
  mcpSignOut: (name: string) => invoke<McpServer[]>('mcp_sign_out', { name }),
  /** Whether the open project is trusted, and which `.mcp.json` servers and hooks it would run. */
  projectTrustStatus: () => invoke<TrustStatus>('project_trust_status'),
  /** Trusts the open project folder and starts its `.mcp.json` connectors. */
  trustProject: () => invoke<TrustStatus>('trust_project'),
  /** Stops trusting the open project and stops its `.mcp.json` connectors. */
  untrustProject: () => invoke<TrustStatus>('untrust_project'),
  onAgentEvent: (handler: (event: AgentEvent) => void) => listen<AgentEvent>('agent://event', event => handler(event.payload)),
  allowPendingAlways: () => invoke<void>('allow_pending_always'),
  voiceStatus: () => invoke<VoiceView>('voice_status'),
  configureVoice: (baseUrl: string, apiKey: string, model: string) => invoke<VoiceView>('configure_voice', { baseUrl, apiKey, model }),
  transcribeAudio: (audio: number[], mimeType: string) => invoke<string>('transcribe_audio', { audio, mimeType }),
  openUrl: (url: string) => invoke<void>('open_url', { url }),
  stopChat: (sessionId?: string | null) => invoke<void>('stop_chat', { sessionId: sessionId ?? null }),
  steerSession: (sessionId: string, text: string) => invoke<boolean>('steer_session', { sessionId, text }),
  memoryFiles: () => invoke<{ project: string | null; user: string }>('memory_files'),
  openMemoryFile: (scope: 'project' | 'user') => invoke<string>('open_memory_file', { scope }),
  permissionRules: () => invoke<string[]>('permission_rules'),
  revokePermission: (key: string) => invoke<string[]>('revoke_permission', { key }),
  doctor: () => invoke<{ name: string; ok: boolean; detail: string; fix: string }[]>('doctor'),
  runPendingTask: () => invoke<string>('run_pending_task'),
  runTask: (task: string) => invoke<string>('run_task_command', { task }),
  terminalStart: (cwd?: string, launch?: { program: string; args: string[]; env: [string, string][] }) => invoke<string>('terminal_start', { cwd: cwd ?? null, launch: launch ?? null }),
  terminalWrite: (id: string, data: string) => invoke<void>('terminal_write', { id, data }),
  terminalResize: (id: string, cols: number, rows: number) => invoke<void>('terminal_resize', { id, cols, rows }),
  terminalStop: (id: string) => invoke<void>('terminal_stop', { id }),
}
