import { invoke } from '@tauri-apps/api/core'
import { listen } from '@tauri-apps/api/event'
import type { AgentEvent, AgentMode, AgentView, ShellView, AgentResponse, AttachedDocument, CheckProgress, CliStatus, CheckSummary, ContextUsage, Effort, PrStatus, SessionChange, SlashCommand, FileEntry, GitStatus, McpServer, ModelInfo, ProbeResult, ProjectInfo, ProviderView, RemoteInfo, RewindResult, SearchResults, IndexStatus, SessionSnapshot, SessionSummary, SkillView, TrustStatus, VoiceView } from './types'
import type { ApiFormat } from './providerCatalog'
import type { Route } from './lib/browser'

export const api = {
  currentProject: () => invoke<ProjectInfo | null>('current_project'),
  recentProjects: () => invoke<string[]>('recent_projects'),
  listSessions: () => invoke<SessionSummary[]>('list_sessions'),
  listAllSessions: () => invoke<SessionSummary[]>('list_all_sessions'),
  currentSession: () => invoke<SessionSnapshot | null>('current_session'),
  createSession: (worktree = false) => invoke<SessionSnapshot>('create_session', { worktree }),
  createChatSession: () => invoke<SessionSnapshot>('create_chat_session'),
  sessionSnapshot: (id: string) => invoke<SessionSnapshot>('session_snapshot', { id }),
  rewindSession: (userIndex: number, restoreCode: boolean) => invoke<RewindResult>('rewind_session', { userIndex, restoreCode }),
  sessionContext: (sessionId: string) => invoke<ContextUsage>('session_context', { sessionId }),
  compactSession: (sessionId: string) => invoke<ContextUsage>('compact_session', { sessionId }),
  /** Asks the provider for the model's window and the key's quotas, then returns the session's use. */
  refreshContext: (sessionId: string | null) => invoke<ContextUsage>('refresh_context', { sessionId }),
  sessionChanges: () => invoke<SessionChange[]>('session_changes'),
  listCommands: () => invoke<SlashCommand[]>('list_commands'),
  expandCommand: (name: string, args: string) => invoke<string>('expand_command', { name, args }),
  pullRequestStatus: () => invoke<PrStatus | null>('pull_request_status'),
  failedCheckLog: () => invoke<string>('failed_check_log'),
  selectSession: (id: string) => invoke<SessionSnapshot>('select_session', { id }),
  renameSession: (id: string, title: string) => invoke<SessionSummary>('rename_session', { id, title }),
  /** Asks the model for a short task title after the first reply; null when already titled. */
  listSkills: () => invoke<SkillView[]>('list_skills'),
  importSkills: (paths: string[]) => invoke<SkillView[]>('import_skills', { paths }),
  removeSkill: (name: string) => invoke<SkillView[]>('remove_skill', { name }),
  openSkillsFolder: () => invoke<void>('open_skills_folder'),
  setSkillEnabled: (name: string, enabled: boolean) => invoke<SkillView[]>('set_skill_enabled', { name, enabled }),
  /** Custom sub-agents of the open project, plus personal ones. */
  listAgents: () => invoke<AgentView[]>('list_agents'),
  /** Commands the agent left running in the background; one session's when given. */
  listShells: (sessionId?: string) => invoke<ShellView[]>('list_shells', { sessionId: sessionId ?? null }),
  stopShell: (id: string) => invoke<void>('stop_shell', { id }),
  cliStatus: () => invoke<CliStatus>('cli_status'),
  /** Puts the CLI bundled with this app on the PATH. */
  cliInstallPath: () => invoke<CliStatus>('cli_install_path'),
  autoTitleSession: (sessionId: string) => invoke<SessionSummary | null>('auto_title_session', { sessionId }),
  deleteSession: (id: string) => invoke<SessionSnapshot>('delete_session', { id }),
  // The project's own .mcp.json connectors follow the open project; they reconnect in the background.
  openProject: (path: string) => invoke<ProjectInfo>('open_project', { path }).then(info => { void invoke('mcp_sync_project').catch(() => undefined); return info }),
  cloneProject: (url: string, destination: string) => invoke<ProjectInfo>('clone_project', { url, destination }),
  listDirectory: (path?: string) => invoke<FileEntry[]>('list_directory', { path }),
  readFile: (path: string) => invoke<string>('read_file', { path }),
  searchText: (query: string, options: { caseSensitive?: boolean; wholeWord?: boolean; regex?: boolean; glob?: string } = {}) => invoke<SearchResults>('search_text', { query, ...options }),
  listProjectFiles: () => invoke<string[]>('list_project_files'),
  indexStatus: () => invoke<IndexStatus>('index_status'),
  /** Checks the disk for edits made outside Neru; the tree hears about them through workspace://changed. */
  indexRefresh: () => invoke<IndexStatus>('index_refresh'),
  /** Fuzzy file finder over the project index, best match first. */
  searchFiles: (query: string, limit = 60) => invoke<string[]>('search_files', { query, limit }),
  gitStatus: () => invoke<GitStatus>('git_status'),
  gitDiff: (path?: string, staged = false) => invoke<string>('git_diff', { path, staged }),
  gitStage: (path: string) => invoke<void>('git_stage', { path }),
  gitUnstage: (path: string) => invoke<void>('git_unstage', { path }),
  gitCommit: (message: string) => invoke<string>('git_commit', { message }),
  gitBranches: () => invoke<string[]>('git_branches'),
  gitCreateBranch: (name: string) => invoke<string>('git_create_branch', { name }),
  gitRemoteInfo: () => invoke<RemoteInfo>('git_remote_info'),
  gitPush: () => invoke<string>('git_push'),
  createPullRequest: (title?: string, body?: string) => invoke<{ url: string; created: boolean }>('create_pull_request', { title, body }),
  mergePullRequest: () => invoke<string>('merge_pull_request'),
  gitFetch: () => invoke<string>('git_fetch'),
  gitPull: () => invoke<string>('git_pull'),
  gitCheckout: (name: string) => invoke<string>('git_checkout', { name }),
  gitMerge: (name: string) => invoke<string>('git_merge', { name }),
  gitRebase: (name: string) => invoke<string>('git_rebase', { name }),
  gitStash: (action: 'push' | 'pop') => invoke<string>('git_stash', { action }),
  saveFile: (path: string, content: string) => invoke<string>('save_file', { path, content }),
  openInEditor: (path: string) => invoke<void>('open_in_editor', { path }),
  forgetProject: (path: string) => invoke<string[]>('forget_project', { path }),
  revealPath: (path: string) => invoke<void>('reveal_path', { path }),
  fileAction: (action: 'new_file' | 'new_folder' | 'rename' | 'duplicate' | 'delete', path: string, to?: string) => invoke<string>('file_action', { action, path, to: to ?? null }),
  previewHint: () => invoke<{ command: string; url: string }>('preview_hint'),
  previewStart: () => invoke<{ command: string; url: string }>('preview_start'),
  previewCurrent: () => invoke<{ command: string; url: string } | null>('preview_current'),
  previewStop: () => invoke<void>('preview_stop'),
  previewRoute: (url: string) => invoke<Route>('preview_route', { url }),
  proposeFile: (path: string, content: string) => invoke<{ diff: string }>('propose_file', { path, content }),
  applyPending: () => invoke<string>('apply_pending'),
  rejectPending: () => invoke<void>('reject_pending'),
  /** Answers a plan from exit_plan_mode; returns the mode the session continues in. */
  resolvePlan: (sessionId: string | null, approve: boolean, mode: AgentMode | null, feedback: string | null) => invoke<AgentMode>('resolve_plan', { sessionId, approve, mode, feedback }),
  /** One answer per question; several choices joined by ", ". */
  answerQuestion: (sessionId: string | null, answers: string[]) => invoke<void>('answer_question', { sessionId, answers }),
  restoreCheckpoint: (id: string) => invoke<void>('restore_checkpoint', { id }),
  configureProvider: (providerId: string, apiFormat: ApiFormat, baseUrl: string, apiKey: string, model: string) => invoke<ProviderView>('configure_provider', { providerId, apiFormat, baseUrl, apiKey, model }),
  providerStatus: () => invoke<ProviderView>('provider_status'),
  newChat: () => invoke<void>('new_chat'),
  forkSession: (id: string) => invoke<SessionSnapshot>('fork_session', { id }),
  listModels: (providerId: string, apiFormat: ApiFormat, baseUrl: string, apiKey: string) => invoke<ModelInfo[]>('list_models', { providerId, apiFormat, baseUrl, apiKey }),
  probeModel: (providerId: string, apiFormat: ApiFormat, baseUrl: string, apiKey: string, model: string, force = false) => invoke<ProbeResult>('probe_model', { providerId, apiFormat, baseUrl, apiKey, model, force }),
  checkModels: (runId: string, providerId: string, baseUrl: string, apiKey: string, targets: { model: string; apiFormat: ApiFormat }[]) => invoke<CheckSummary>('check_models', { runId, providerId, baseUrl, apiKey, targets }),
  cancelCheckModels: (runId: string) => invoke<void>('cancel_check_models', { runId }),
  onModelCheck: (handler: (progress: CheckProgress) => void) => listen<CheckProgress>('models://check', event => handler(event.payload)),
  chat: (options: { prompt: string; contextPaths: string[]; mode: AgentMode; web: boolean; documents: AttachedDocument[]; effort: Effort; sessionId: string | null; notes?: string | null; surface?: 'chat' | 'code' }) => invoke<AgentResponse>('ai_chat', {
    prompt: options.prompt, contextPaths: options.contextPaths, mode: options.mode, web: options.web, surface: options.surface ?? 'code',
    documents: options.documents.filter(doc => doc.kind !== 'image').map(doc => ({ path: doc.path, text: doc.text ?? null, name: doc.kind === 'element' ? doc.name : null, kind: doc.kind === 'element' ? 'element' : null })),
    images: options.documents.filter(doc => doc.kind === 'image' && doc.dataUrl).map(doc => ({ name: doc.name, dataUrl: doc.dataUrl })),
    effort: options.effort === 'auto' ? null : options.effort, sessionId: options.sessionId, notes: options.notes ?? null,
  }),
  inspectDocuments: (paths: string[]) => invoke<AttachedDocument[]>('inspect_documents', { paths }),
  documentBytes: (path: string) => invoke<ArrayBuffer>('document_bytes', { path }),
  readImage: (path: string) => invoke<string>('read_image', { path }),
  effortSupported: () => invoke<boolean>('effort_supported'),
  forgetKeys: () => invoke<void>('forget_keys'),
  mcpServers: () => invoke<McpServer[]>('mcp_servers'),
  mcpSaveServer: (server: Pick<McpServer, 'name' | 'command' | 'args' | 'env' | 'url' | 'headers' | 'enabled'>, previous?: string) => invoke<McpServer[]>('mcp_save_server', { server, previous }),
  mcpRemoveServer: (name: string) => invoke<McpServer[]>('mcp_remove_server', { name }),
  mcpRestart: (name: string) => invoke<McpServer[]>('mcp_restart', { name }),
  mcpSyncProject: () => invoke<McpServer[]>('mcp_sync_project'),
  mcpSignIn: (name: string) => invoke<McpServer[]>('mcp_sign_in', { name }),
  mcpSignOut: (name: string) => invoke<McpServer[]>('mcp_sign_out', { name }),
  /** Whether the open project is trusted, and which `.mcp.json` servers and hooks it would run. */
  projectTrustStatus: () => invoke<TrustStatus>('project_trust_status'),
  /** Trusts the open project folder and starts its `.mcp.json` connectors. */
  trustProject: () => invoke<TrustStatus>('trust_project'),
  onAgentEvent: (handler: (event: AgentEvent) => void) => listen<AgentEvent>('agent://event', event => handler(event.payload)),
  allowPendingAlways: () => invoke<void>('allow_pending_always'),
  voiceStatus: () => invoke<VoiceView>('voice_status'),
  configureVoice: (baseUrl: string, apiKey: string, model: string) => invoke<VoiceView>('configure_voice', { baseUrl, apiKey, model }),
  transcribeAudio: (audio: number[], mimeType: string) => invoke<string>('transcribe_audio', { audio, mimeType }),
  openUrl: (url: string) => invoke<void>('open_url', { url }),
  stopChat: (sessionId?: string | null) => invoke<void>('stop_chat', { sessionId: sessionId ?? null }),
  steerSession: (sessionId: string, text: string) => invoke<boolean>('steer_session', { sessionId, text }),
  memoryFiles: () => invoke<{ project: string | null; user: string }>('memory_files'),
  openMemoryFile: (scope: 'project' | 'user') => invoke<string>('open_memory_file', { scope }),
  permissionRules: () => invoke<string[]>('permission_rules'),
  revokePermission: (key: string) => invoke<string[]>('revoke_permission', { key }),
  doctor: () => invoke<{ name: string; ok: boolean; detail: string; fix: string }[]>('doctor'),
  runPendingTask: () => invoke<string>('run_pending_task'),
  runTask: (task: string) => invoke<string>('run_task_command', { task }),
  terminalStart: () => invoke<string>('terminal_start'),
  terminalWrite: (id: string, data: string) => invoke<void>('terminal_write', { id, data }),
  terminalResize: (id: string, cols: number, rows: number) => invoke<void>('terminal_resize', { id, cols, rows }),
  terminalStop: (id: string) => invoke<void>('terminal_stop', { id }),
}
